### ISSUE TITLE
View area gradually shrinks when browser is resized

### ISSUE THREAD

**Issue by fenomas** [matthijsgroen/geppetto-player#6]
Hi, very cool project!

I noticed that when I open the [homepage demo](https://geppetto.js.org/), if I resize the browser window (horizontally) a bunch of times, the displayed animation gets gradually smaller and smaller.

I haven't looked closely, but at first glance it looks like the canvas itself is getting vertically smaller, so I imagine it's a CSS issue with the page, rather than a problem with the rendering per se.

Tested in current Chrome on PC.

**Comment by matthijsgroen** [comment]
Hmm I can't seem to reproduce it..

**Comment by andyhall** [comment]
It's very gradual - if I resize the browser window (horizontally) from quite large to quite small, and then back, the displayed image gets a few pixels smaller. But if I repeat it a bunch of times the canvas keeps getting smaller and smaller.

Now that I check, it only reproduces for me on PC - no issue on chrome/Mac. Could just be a chrome bug..

**Comment by matthijsgroen** [comment]
Could be, I don't recall having any special resizing code in there. Interesting none the less... Let's wait for a next chrome release and re-evaluate. I think it is outside of this project scope.  (I do want to change the main website to be based on docusaurus in the future, maybe that can solve some issues as well)

**Comment by andyhall** [comment]
No idea if the project's rendering is involved, but curiously I noticed that the canvas isn't *just* scaled down; the illustration parts seem to be affected differently. Here are some images, if you don't have windows handy to check:

Initially:

![image](https://user-images.githubusercontent.com/352373/126156428-eceee188-6827-4930-9e27-fa9c6693f84c.png)

After resizing a bunch of times - note the woman and the cloud.

![image](https://user-images.githubusercontent.com/352373/126156673-27d91629-d874-44a6-a42c-cf5558c27095.png)

Reloading the page fixes things, so just an FYI I guess.

**Comment by matthijsgroen** [comment]
Its not an issue of the player, the issue was in the updating of width/height of the geppetto website. Adding a `aspect-ratio: 2 / 1;` seems to fix it: https://github.com/matthijsgroen/geppetto/commit/b24b0410997e96d74864cb26b1f351ac37149377

@fenomas  can you verify?

**Comment by fenomas** [comment]
Yes, issue is fixed. Lovely project by the way and thanks for checking!
